name: Dependabot Alerts → Jira (scheduled)

on:
  schedule:
    - cron: '37 7 * * 1-5'
  workflow_dispatch: {}

permissions:
  contents: read
  security-events: read

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot alerts → Jira (bulk)
        uses: ndustrialio/actions/vulnerability-scan/dependabot@vulns-to-jira
        with:
          github-token: ${{ secrets.NIO_BOT_TOKEN }}
          bulk-parallel: "12"        # tweak as you like
          jira-base-url:  ${{ secrets.JIRA_BASE_URL }}
          jira-email:     ${{ secrets.JIRA_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          jira-team-name: 'Foundry'
          jira-assignee-account-id: "5ede862e9c72bd0ac04418fd"
